Repository MasterSteelblade/Waterfall, pull requests merged in 2021-03, with the labels that each got.

#14 Add working TOTP 2FA support
  html/process/settings/twoFactor_disable.php
  html/process/settings/twoFactor_enable.php
  html/process/user/login.php
  html/settings/twoFactor.php
  html/settings/user.php
  src/classes/User.class.php
Labels: Waterfall 1.1

#16 Make Sentry optional when ENVIRONMENT=dev
  src/loader.php
Labels: Waterfall 1.1

#15 Improve setup documentation
  docs/SETUP.md
Labels: Waterfall 1.1

#19 Fixed account deleting
  html/policy/bugbounty.php
  html/process/user/delete.php
Labels: Waterfall 1.1

#21 Fix searching being case sensitive.
  src/classes/PostCollector.class.php
Labels: Waterfall 1.2

#23 Post buttons will change when you press now to let you know it's doing something
  html/message.php
  html/post/answer.php
  html/post/art.php
  html/post/audio.php
  html/post/edit.php
  html/post/image.php
  html/post/link.php
  html/post/quote.php
  html/post/reblog.php
  html/post/text.php
  html/post/video.php
Labels: Waterfall 1.2

#24 Separated out language checks
  .github/workflows/language.yml
  .github/workflows/tests.yml
Labels: Waterfall 1.2

#26 (Mostly) Finished localisable strings
  blogs/includes/blogLogin.php
  blogs/includes/header.php
  blogs/includes/maint.php
  blogs/index.php
  blogs/page.php
  blogs/post.php
  blogs/tagged.php
  html/dashboard.php
  html/discovery.php
  html/drafts.php
  html/followers.php
  html/following.php
  html/inbox.php
  html/includes/footer.php
  html/includes/header.php
  html/includes/maint.php
  html/index.php
  html/liked.php
  html/login.php
  html/logout.php
  html/message.php
  html/outbox.php
  html/page/edit.php
  html/page/new.php
  html/policy/terms-of-service.php
  html/post/answer.php
  html/post/art.php
  html/post/audio.php
  html/post/edit.php
  html/post/image.php
  html/post/link.php
  html/post/quote.php
  html/post/reblog.php
  html/post/text.php
  html/post/video.php
  html/queue.php
  html/register.php
  html/search.php
  html/settings/blog.php
  html/settings/group_permissions.php
  html/settings/newBlog.php
  html/settings/twoFactor.php
  html/settings/user.php
  html/user/forgottenPassword.php
  html/user/update.php
  lang/TRANSLATORS.md
  lang/lang_en.ini
  src/classes/Note.class.php
  src/classes/Post.class.php
Labels: Waterfall 1.2

#27 Fixed error spam related to non-existent blogs.
  blogs/includes/header.php
Labels: Waterfall 1.2

#28 Finally finished string localisation and added TRANSLATORS.md
  html/process/blog/delete.php
  html/process/blog/login.php
  html/process/blog/message.php
  html/process/blog/toggle-follow.php
  html/process/messages/delete_inbox.php
  html/process/messages/delete_outbox.php
  html/process/page/edit.php
  html/process/page/new.php
  html/process/poll/vote.php
  html/process/post/answer.php
  html/process/post/art.php
  html/process/post/audio.php
  html/process/post/comment.php
  html/process/post/delete.php
  html/process/post/edit.php
  html/process/post/image.php
  html/process/post/link.php
  html/process/post/quote.php
  html/process/post/reblog.php
  html/process/post/text.php
  html/process/post/toggle-like.php
  html/process/post/tool/link-scraper.php
  html/process/post/video.php
  html/process/settings/block.php
  html/process/settings/blog.php
  html/process/settings/delete_blog.php
  html/process/settings/group_permissions.php
  html/process/settings/invite_blog.php
  html/process/settings/invite_create.php
  html/process/settings/join_blog.php
  html/process/settings/leave_blog.php
  html/process/settings/new_blog.php
  html/process/settings/remove_member.php
  html/process/settings/remove_password.php
  html/process/settings/twoFactor_disable.php
  html/process/settings/twoFactor_enable.php
  html/process/settings/unblock.php
  html/process/settings/user.php
  html/process/user/delete.php
  html/process/user/login.php
  html/process/user/logout.php
  html/process/user/register.php
  html/process/user/request_reset.php
  html/process/user/switch.php
  html/process/user/update.php
  html/settings/blog.php
  html/settings/group_permissions.php
  html/settings/user.php
  lang/TRANSLATORS.md
  lang/lang_en.ini
Labels: Waterfall 1.2

#29 Updating Test Strategy
  .github/workflows/minify.yml
  .github/workflows/tests.yml
  README.md
  src/classes/User.class.php
  tests/prep/testPrep.php
Labels: Waterfall 1.2

#30 Added page deletion
  html/page/edit.php
  html/page/new.php
  html/process/page/delete.php
  html/settings/blog.php
  lang/lang_en.ini
  src/classes/Page.class.php
  src/classes/Post.class.php
Labels: Waterfall 1.2

#31 Update Pillow version for Raven
  raven/requirements.txt
Labels: Waterfall 1.2

#32 Adding PHPStan to test coverage
  .github/workflows/tests.yml
  blogs/includes/header.php
  blogs/page.php
  blogs/post.php
  html/process/blog/message.php
  html/process/blog/toggle-follow.php
  html/process/page/new.php
  html/process/post/image.php
  html/process/post/tool/link-scraper.php
  html/process/settings/new_blog.php
  html/process/settings/user.php
  html/settings/twoFactor.php
  html/settings/user.php
  lang/lang_en.ini
  src/classes/Badge.class.php
  src/classes/Blog.class.php
  src/classes/BlogMember.class.php
  src/classes/DatabaseCollector.class.php
  src/classes/EmailMessage.class.php
  src/classes/Emoji.class.php
  src/classes/KestrelEvent.class.php
  src/classes/Message.class.php
  src/classes/Note.class.php
  src/classes/Poll.class.php
  src/classes/Post.class.php
  src/classes/PostCollector.class.php
  src/classes/Serial.class.php
  src/classes/Session.class.php
  src/classes/Tag.class.php
  src/classes/User.class.php
  src/classes/WFAudio.class.php
  src/classes/WFAvatar.class.php
  src/classes/WFRedis.class.php
  src/classes/WFText.class.php
  src/classes/WFVideo.class.php
  src/classes/WaterfallKestrel.class.php
  src/classes/api/APIMessage.class.php
  src/classes/api/APINote.class.php
  src/classes/api/APIPost.class.php
  src/classes/i18n.class.php
  src/classes/posts/AnswerPost.class.php
  src/loader.php
Labels: Waterfall 1.2

#34 Re-added mutual notes mode, renamed to "notes from people I follow"
  blogs/includes/header.php
  html/dashboard.php
  html/process/settings/user.php
  html/settings/blog.php
  html/settings/user.php
  lang/lang_en.ini
  src/classes/PostCollector.class.php
Labels: Waterfall 1.2

#35 Re-added OC Only mode
  html/dashboard.php
  html/process/settings/user.php
  html/settings/user.php
  lang/lang_en.ini
  src/classes/PostCollector.class.php
Labels: Waterfall 1.2

#36 (Probably) Fixed blocking
  blogs/includes/header.php
  html/message.php
  html/process/blog/message.php
  html/process/blog/toggle-follow.php
  src/classes/BlockManager.class.php
  src/classes/PostCollector.class.php
  src/classes/User.class.php
  tests/UserTest.php
Labels: Waterfall 1.2

#39 Fixed video success giving undefined message
  html/process/post/video.php
Labels: Waterfall 1.3

#40 Remove unused CSS and font files, update TRANSLATORS.md to provide a primer on Git
  blogs/includes/header.php
  html/css/font/css/all.css
  html/css/font/css/duotone.css
  html/css/font/css/light.css
  html/css/font/css/regular.css
  html/css/font/css/thin.css
  html/css/font/webfonts/fa-brands-400.eot
  html/css/font/webfonts/fa-brands-400.svg
  html/css/font/webfonts/fa-brands-400.ttf
  html/css/font/webfonts/fa-brands-400.woff
  html/css/font/webfonts/fa-brands-400.woff2
  html/css/font/webfonts/fa-duotone-900.eot
  html/css/font/webfonts/fa-duotone-900.svg
  html/css/font/webfonts/fa-duotone-900.ttf
  html/css/font/webfonts/fa-duotone-900.woff
  html/css/font/webfonts/fa-duotone-900.woff2
  html/css/font/webfonts/fa-light-300.eot
  html/css/font/webfonts/fa-light-300.svg
  html/css/font/webfonts/fa-light-300.ttf
  html/css/font/webfonts/fa-light-300.woff
  html/css/font/webfonts/fa-light-300.woff2
  html/css/font/webfonts/fa-regular-400.eot
  html/css/font/webfonts/fa-regular-400.svg
  html/css/font/webfonts/fa-regular-400.ttf
  html/css/font/webfonts/fa-regular-400.woff
  html/css/font/webfonts/fa-regular-400.woff2
  html/css/font/webfonts/fa-thin-100.eot
  html/css/font/webfonts/fa-thin-100.svg
  html/css/font/webfonts/fa-thin-100.ttf
  html/css/font/webfonts/fa-thin-100.woff
  html/css/font/webfonts/fa-thin-100.woff2
  html/dashboard.php
  html/includes/header.php
  lang/TRANSLATORS.md
  src/classes/Post.class.php
Labels: Waterfall 1.3
